"""unique_constraint_positions_player_ticker

Revision ID: 3fccae9c8d63
Revises: f1d23e3ec558
Create Date: 2026-04-24 23:02:37.748603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fccae9c8d63'
down_revision: Union[str, None] = 'f1d23e3ec558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_player_ticker'), table_name='positions')
    op.create_index('ix_positions_player_ticker', 'positions', ['player_id', 'ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_player_ticker', table_name='positions')
    op.create_index(op.f('ix_positions_player_ticker'), 'positions', ['player_id', 'ticker'], unique=False)
    # ### end Alembic commands ###
