"""add_performance_indexes

Revision ID: 75041f81c664
Revises: c6186616ec13
Create Date: 2026-04-22 09:29:26.462402

"""
from collections.abc import Sequence

from alembic import op

revision: str = '75041f81c664'
down_revision: str | None = 'c6186616ec13'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_player_id'), 'orders', ['player_id'], unique=False)
    op.create_index('ix_orders_player_status', 'orders', ['player_id', 'status'], unique=False)
    op.create_index('ix_orders_status_type', 'orders', ['status', 'order_type'], unique=False)
    op.create_index(op.f('ix_players_competition_id'), 'players', ['competition_id'], unique=False)
    op.create_index(
        'ix_players_competition_spectator', 'players', ['competition_id', 'spectator'],
        unique=False,
    )
    op.create_index(op.f('ix_positions_player_id'), 'positions', ['player_id'], unique=False)
    op.create_index(
        'ix_positions_player_ticker', 'positions', ['player_id', 'ticker'], unique=False
    )
    op.create_index(
        op.f('ix_price_snapshots_competition_id'), 'price_snapshots', ['competition_id'],
        unique=False,
    )
    op.create_index(
        'ix_price_snapshots_competition_ticker_time',
        'price_snapshots',
        ['competition_id', 'ticker', 'recorded_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_snapshots_competition_ticker_time', table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_competition_id'), table_name='price_snapshots')
    op.drop_index('ix_positions_player_ticker', table_name='positions')
    op.drop_index(op.f('ix_positions_player_id'), table_name='positions')
    op.drop_index('ix_players_competition_spectator', table_name='players')
    op.drop_index(op.f('ix_players_competition_id'), table_name='players')
    op.drop_index('ix_orders_status_type', table_name='orders')
    op.drop_index('ix_orders_player_status', table_name='orders')
    op.drop_index(op.f('ix_orders_player_id'), table_name='orders')
    # ### end Alembic commands ###
