"""add_trading_halted_to_player

Revision ID: f22536f6f416
Revises: fb6b585d181e
Create Date: 2026-05-01 13:22:32.772300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f22536f6f416'
down_revision: Union[str, None] = 'fb6b585d181e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("players") as batch_op:
        batch_op.add_column(
            sa.Column("trading_halted", sa.Boolean(), nullable=False, server_default="0")
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'trading_halted')
    # ### end Alembic commands ###
