"""add_ledger_entries_table

Revision ID: fb6b585d181e
Revises: 161a9e33aa20
Create Date: 2026-04-28 10:29:13.441887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb6b585d181e'
down_revision: Union[str, None] = '161a9e33aa20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
